# Generated by Django 5.1 on 2024-10-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_user_links_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='last_check',
            field=models.DateField(),
        ),
    ]
