# Generated by Django 5.1 on 2024-10-08 22:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_links_last_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='last_check',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
