# Generated by Django 5.1 on 2024-10-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_links_last_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='last_check',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
