# Generated by Django 5.1 on 2024-09-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['applied_date']},
        ),
    ]
